#!/bin/bash
#
# Copyright (c) 2020, The Linux Foundation. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above
#       copyright notice, this list of conditions and the following
#       disclaimer in the documentation and/or other materials provided
#       with the distribution.
#     * Neither the name of The Linux Foundation nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT
# ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

target_dir=$1

MSM_HEADER_ARCH='aarch64'
MSM_HEADER_DIR='/usr/src/header'

MSM_HEADER_CHECK_FILE_ARRAY=(bin2c dtc kallsyms pnmtologo conmakehash \
				recordmcount sortextable asn1_compiler \
				mk_elfconfig modpost fixdep conf mdp \
				genheaders sign-file)
apt_update ()
{
	echo "apt update..."
	apt update
	if [ $? != 0 ]; then
		echo "apt update failed..."
		return 1
	else
		return 0
	fi
}

flex_install ()
{
	echo "Checking for flex..."
	if [ -x "$(command -v flex)" ]; then
		return 0
	else
		apt-get -y install flex
		if [ $? != 0 ]; then
			echo "Flex install failed..."
			return 1
		else
			return 0
		fi
	fi
}

bison_install ()
{
	echo "Checking for bison..."
	if [ -x "$(command -v bison)" ]; then
		return 0
	else
		apt-get -y install bison
		if [ $? != 0 ]; then
			echo "Bison install failed..."
			return 1
		else
			return 0
		fi
	fi
}


#if the "/usr/src/header" directory did not exist,exit.
if [ ! -d ${MSM_HEADER_DIR} ]; then
	echo "No /usr/src/header directory..."
	exit 1
fi

apt_update
exitcode_update=$?

flex_install
exitcode_flex=$?

bison_install
exitcode_bison=$?

if [[ ${exitcode_update} = "0" && ${exitcode_flex} = "0" && ${exitcode_bison} = "0"]]; then

	echo "Detected flex,bison..."

	#Whether the architecture of the files in the list is ${MSM_HEADER_ARCH}
	for elf_file in ${MSM_HEADER_CHECK_FILE_ARRAY[@]}; do
		        var=$(find "${MSM_HEADER_DIR}/scripts" -type f -name "$elf_file" | \
					xargs file | \
					sed 's/ /\n/g' | \
					grep -i ${MSM_HEADER_ARCH} )

		if [[ ${var:0:7} != ${MSM_HEADER_ARCH} ]]; then
			cd ${MSM_HEADER_DIR}
			make scripts -j8
			exit 0
		fi
	done

else
	echo "Please check apt-get install for flex,bison..."
	exit 1
fi

