TARGET_SYS = "${TARGET_ARCH}-linux-gnu"
TARGET_CFLAGS += "-I${STAGING_INCDIR}/c++"
TARGET_CFLAGS += "-I${STAGING_INCDIR}/c++/backward"
TARGET_LDFLAGS += "-L${STAGING_LIBDIR}/${TARGET_ARCH}-linux-gnu"

